[package]
  cjc-version = "1.0.0"
  name = "cnslookup"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
dnsmsg = { git = "https://github.com/hiung/dnsmsg.git" } 
