[package]
  cjc-version = "1.0.0"
  name = "cnslookup"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
dnsmsg = { git = "https://github.com/hiung/dnsmsg.git" } 

[target.x86_64-w64-mingw32]                                              
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["D:\\Application\\cangjie\\modules\\windows_x86_64_llvm\\stdx\\dynamic\\stdx"] 